-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GAT_compute_one_graph_compute_out_nodes_features_Pipeline_VITIS_LOOP_154_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    mul_ln1169_1 : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln150 : IN STD_LOGIC_VECTOR (2 downto 0);
    trunc_ln : IN STD_LOGIC_VECTOR (3 downto 0);
    sum_V_2_out : OUT STD_LOGIC_VECTOR (27 downto 0);
    sum_V_2_out_ap_vld : OUT STD_LOGIC;
    all_attention_coefficients_V_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    all_attention_coefficients_V_ce0 : OUT STD_LOGIC;
    all_attention_coefficients_V_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_0_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_0_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_1_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_1_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_2_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_2_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_3_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_3_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_4_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_4_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_5_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_5_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_6_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_6_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_7_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_7_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_8_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_8_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_9_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_9_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_10_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_10_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_11_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_11_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_12_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_12_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_13_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_13_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_14_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_14_q0 : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    nodes_features_proj_V_15_ce0 : OUT STD_LOGIC;
    nodes_features_proj_V_15_q0 : IN STD_LOGIC_VECTOR (27 downto 0) );
end;


architecture behav of GAT_compute_one_graph_compute_out_nodes_features_Pipeline_VITIS_LOOP_154_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_13 : STD_LOGIC_VECTOR (4 downto 0) := "10011";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln154_fu_371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln154_reg_545 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln154_reg_545_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_reg_634 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_fu_441_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_reg_639 : STD_LOGIC_VECTOR (27 downto 0);
    signal r_V_7_fu_484_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal r_V_7_reg_644 : STD_LOGIC_VECTOR (45 downto 0);
    signal zext_ln1169_7_fu_393_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln1171_3_fu_416_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal lhs_fu_100 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal n2_fu_104 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_n2_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln154_fu_377_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal zext_ln1169_fu_383_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1169_fu_387_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_398_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln1171_fu_406_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln150_cast_fu_354_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln1171_fu_410_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal lhs_2_fu_493_p3 : STD_LOGIC_VECTOR (45 downto 0);
    signal ret_V_fu_501_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component GAT_compute_one_graph_mux_164_28_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (27 downto 0);
        din1 : IN STD_LOGIC_VECTOR (27 downto 0);
        din2 : IN STD_LOGIC_VECTOR (27 downto 0);
        din3 : IN STD_LOGIC_VECTOR (27 downto 0);
        din4 : IN STD_LOGIC_VECTOR (27 downto 0);
        din5 : IN STD_LOGIC_VECTOR (27 downto 0);
        din6 : IN STD_LOGIC_VECTOR (27 downto 0);
        din7 : IN STD_LOGIC_VECTOR (27 downto 0);
        din8 : IN STD_LOGIC_VECTOR (27 downto 0);
        din9 : IN STD_LOGIC_VECTOR (27 downto 0);
        din10 : IN STD_LOGIC_VECTOR (27 downto 0);
        din11 : IN STD_LOGIC_VECTOR (27 downto 0);
        din12 : IN STD_LOGIC_VECTOR (27 downto 0);
        din13 : IN STD_LOGIC_VECTOR (27 downto 0);
        din14 : IN STD_LOGIC_VECTOR (27 downto 0);
        din15 : IN STD_LOGIC_VECTOR (27 downto 0);
        din16 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component GAT_compute_one_graph_mul_28s_28s_46_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (27 downto 0);
        din1 : IN STD_LOGIC_VECTOR (27 downto 0);
        dout : OUT STD_LOGIC_VECTOR (45 downto 0) );
    end component;


    component GAT_compute_one_graph_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_164_28_1_1_U1039 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_0_q0,
        din1 => nodes_features_proj_V_1_q0,
        din2 => nodes_features_proj_V_2_q0,
        din3 => nodes_features_proj_V_3_q0,
        din4 => nodes_features_proj_V_4_q0,
        din5 => nodes_features_proj_V_5_q0,
        din6 => nodes_features_proj_V_6_q0,
        din7 => nodes_features_proj_V_7_q0,
        din8 => nodes_features_proj_V_8_q0,
        din9 => nodes_features_proj_V_9_q0,
        din10 => nodes_features_proj_V_10_q0,
        din11 => nodes_features_proj_V_11_q0,
        din12 => nodes_features_proj_V_12_q0,
        din13 => nodes_features_proj_V_13_q0,
        din14 => nodes_features_proj_V_14_q0,
        din15 => nodes_features_proj_V_15_q0,
        din16 => trunc_ln,
        dout => tmp_fu_441_p18);

    mul_28s_28s_46_1_1_U1040 : component GAT_compute_one_graph_mul_28s_28s_46_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        dout_WIDTH => 46)
    port map (
        din0 => tmp_reg_639,
        din1 => r_V_reg_634,
        dout => r_V_7_fu_484_p2);

    flow_control_loop_pipe_sequential_init_U : component GAT_compute_one_graph_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    lhs_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    lhs_fu_100 <= ap_const_lv28_0;
                elsif ((ap_enable_reg_pp0_iter3 = ap_const_logic_1)) then 
                    lhs_fu_100 <= ret_V_fu_501_p2(45 downto 18);
                end if;
            end if; 
        end if;
    end process;

    n2_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln154_fu_371_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    n2_fu_104 <= add_ln154_fu_377_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n2_fu_104 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln154_reg_545 <= icmp_ln154_fu_371_p2;
                icmp_ln154_reg_545_pp0_iter1_reg <= icmp_ln154_reg_545;
                r_V_reg_634 <= all_attention_coefficients_V_q0;
                tmp_reg_639 <= tmp_fu_441_p18;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                r_V_7_reg_644 <= r_V_7_fu_484_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1169_fu_387_p2 <= std_logic_vector(unsigned(mul_ln1169_1) + unsigned(zext_ln1169_fu_383_p1));
    add_ln1171_fu_410_p2 <= std_logic_vector(unsigned(zext_ln1171_fu_406_p1) + unsigned(zext_ln150_cast_fu_354_p1));
    add_ln154_fu_377_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_n2_1) + unsigned(ap_const_lv5_1));
    all_attention_coefficients_V_address0 <= zext_ln1169_7_fu_393_p1(16 - 1 downto 0);

    all_attention_coefficients_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            all_attention_coefficients_V_ce0 <= ap_const_logic_1;
        else 
            all_attention_coefficients_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln154_fu_371_p2)
    begin
        if (((icmp_ln154_fu_371_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_n2_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, n2_fu_104)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_n2_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_n2_1 <= n2_fu_104;
        end if; 
    end process;

    icmp_ln154_fu_371_p2 <= "1" when (ap_sig_allocacmp_n2_1 = ap_const_lv5_13) else "0";
    lhs_2_fu_493_p3 <= (lhs_fu_100 & ap_const_lv18_0);
    nodes_features_proj_V_0_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_0_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_10_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_10_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_10_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_11_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_11_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_11_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_12_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_12_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_12_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_13_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_13_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_13_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_14_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_14_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_14_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_15_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_15_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_15_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_1_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_1_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_2_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_2_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_3_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_3_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_4_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_4_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_5_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_5_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_6_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_6_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_7_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_7_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_8_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_8_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_8_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    nodes_features_proj_V_9_address0 <= zext_ln1171_3_fu_416_p1(9 - 1 downto 0);

    nodes_features_proj_V_9_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            nodes_features_proj_V_9_ce0 <= ap_const_logic_1;
        else 
            nodes_features_proj_V_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ret_V_fu_501_p2 <= std_logic_vector(unsigned(lhs_2_fu_493_p3) + unsigned(r_V_7_reg_644));
    sum_V_2_out <= lhs_fu_100;

    sum_V_2_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln154_reg_545_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln154_reg_545_pp0_iter1_reg = ap_const_lv1_1))) then 
            sum_V_2_out_ap_vld <= ap_const_logic_1;
        else 
            sum_V_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_s_fu_398_p3 <= (ap_sig_allocacmp_n2_1 & ap_const_lv2_0);
    zext_ln1169_7_fu_393_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1169_fu_387_p2),64));
    zext_ln1169_fu_383_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_n2_1),16));
    zext_ln1171_3_fu_416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1171_fu_410_p2),64));
    zext_ln1171_fu_406_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_398_p3),8));
    zext_ln150_cast_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln150),8));
end behav;
