-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
-- Version: 2021.1
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity GAT_compute_one_graph_compute_out_nodes_features_Pipeline_VITIS_LOOP_164_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    nodes_features_proj_V_0_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_0_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    trunc_ln1171_1 : IN STD_LOGIC_VECTOR (3 downto 0);
    all_attention_coefficients_buffer_V_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    all_attention_coefficients_buffer_V_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_1_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_2_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_3_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_4_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_5_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_6_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_7_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_8_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_9_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_10_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_11_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_12_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_13_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_14_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_0_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_1_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_2_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_3_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_4_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_5_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_6_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_7_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_8_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_9_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_10_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_11_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_12_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_13_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_14_load : IN STD_LOGIC_VECTOR (27 downto 0);
    nodes_features_proj_V_15_15_load : IN STD_LOGIC_VECTOR (27 downto 0);
    sum_V_4_out : OUT STD_LOGIC_VECTOR (27 downto 0);
    sum_V_4_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of GAT_compute_one_graph_compute_out_nodes_features_Pipeline_VITIS_LOOP_164_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln164_fu_2325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln164_reg_3055 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1169_fu_2337_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_V_fu_2341_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal r_V_reg_3063 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_14_fu_2379_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_13_fu_2417_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_12_fu_2455_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_11_fu_2493_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_10_fu_2531_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_7_fu_2569_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_6_fu_2607_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_5_fu_2645_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_4_fu_2683_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_3_fu_2721_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_2_fu_2759_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_1_fu_2797_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_s_fu_2835_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_9_fu_2873_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_8_fu_2911_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_fu_2949_p18 : STD_LOGIC_VECTOR (27 downto 0);
    signal r_V_8_fu_2999_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal r_V_8_reg_3148 : STD_LOGIC_VECTOR (45 downto 0);
    signal ap_phi_reg_pp0_iter0_phi_ln1171_reg_2275 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 : STD_LOGIC_VECTOR (27 downto 0);
    signal lhs_fu_622 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_loop_init : STD_LOGIC;
    signal n2_fu_626 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_n2_2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln164_fu_2331_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal r_V_fu_2341_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal lhs_2_fu_3008_p3 : STD_LOGIC_VECTOR (45 downto 0);
    signal ret_V_fu_3016_p2 : STD_LOGIC_VECTOR (45 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_448 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component GAT_compute_one_graph_mux_164_28_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (27 downto 0);
        din1 : IN STD_LOGIC_VECTOR (27 downto 0);
        din2 : IN STD_LOGIC_VECTOR (27 downto 0);
        din3 : IN STD_LOGIC_VECTOR (27 downto 0);
        din4 : IN STD_LOGIC_VECTOR (27 downto 0);
        din5 : IN STD_LOGIC_VECTOR (27 downto 0);
        din6 : IN STD_LOGIC_VECTOR (27 downto 0);
        din7 : IN STD_LOGIC_VECTOR (27 downto 0);
        din8 : IN STD_LOGIC_VECTOR (27 downto 0);
        din9 : IN STD_LOGIC_VECTOR (27 downto 0);
        din10 : IN STD_LOGIC_VECTOR (27 downto 0);
        din11 : IN STD_LOGIC_VECTOR (27 downto 0);
        din12 : IN STD_LOGIC_VECTOR (27 downto 0);
        din13 : IN STD_LOGIC_VECTOR (27 downto 0);
        din14 : IN STD_LOGIC_VECTOR (27 downto 0);
        din15 : IN STD_LOGIC_VECTOR (27 downto 0);
        din16 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (27 downto 0) );
    end component;


    component GAT_compute_one_graph_mul_28s_28s_46_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (27 downto 0);
        din1 : IN STD_LOGIC_VECTOR (27 downto 0);
        dout : OUT STD_LOGIC_VECTOR (45 downto 0) );
    end component;


    component GAT_compute_one_graph_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_164_28_1_1_U1952 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => all_attention_coefficients_buffer_V_0_load,
        din1 => all_attention_coefficients_buffer_V_1_load,
        din2 => all_attention_coefficients_buffer_V_2_load,
        din3 => all_attention_coefficients_buffer_V_3_load,
        din4 => all_attention_coefficients_buffer_V_4_load,
        din5 => all_attention_coefficients_buffer_V_5_load,
        din6 => all_attention_coefficients_buffer_V_6_load,
        din7 => all_attention_coefficients_buffer_V_7_load,
        din8 => all_attention_coefficients_buffer_V_8_load,
        din9 => all_attention_coefficients_buffer_V_9_load,
        din10 => all_attention_coefficients_buffer_V_10_load,
        din11 => all_attention_coefficients_buffer_V_11_load,
        din12 => all_attention_coefficients_buffer_V_12_load,
        din13 => all_attention_coefficients_buffer_V_13_load,
        din14 => all_attention_coefficients_buffer_V_14_load,
        din15 => all_attention_coefficients_buffer_V_15_load,
        din16 => r_V_fu_2341_p17,
        dout => r_V_fu_2341_p18);

    mux_164_28_1_1_U1953 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_14_0_load,
        din1 => nodes_features_proj_V_14_1_load,
        din2 => nodes_features_proj_V_14_2_load,
        din3 => nodes_features_proj_V_14_3_load,
        din4 => nodes_features_proj_V_14_4_load,
        din5 => nodes_features_proj_V_14_5_load,
        din6 => nodes_features_proj_V_14_6_load,
        din7 => nodes_features_proj_V_14_7_load,
        din8 => nodes_features_proj_V_14_8_load,
        din9 => nodes_features_proj_V_14_9_load,
        din10 => nodes_features_proj_V_14_10_load,
        din11 => nodes_features_proj_V_14_11_load,
        din12 => nodes_features_proj_V_14_12_load,
        din13 => nodes_features_proj_V_14_13_load,
        din14 => nodes_features_proj_V_14_14_load,
        din15 => nodes_features_proj_V_14_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_14_fu_2379_p18);

    mux_164_28_1_1_U1954 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_13_0_load,
        din1 => nodes_features_proj_V_13_1_load,
        din2 => nodes_features_proj_V_13_2_load,
        din3 => nodes_features_proj_V_13_3_load,
        din4 => nodes_features_proj_V_13_4_load,
        din5 => nodes_features_proj_V_13_5_load,
        din6 => nodes_features_proj_V_13_6_load,
        din7 => nodes_features_proj_V_13_7_load,
        din8 => nodes_features_proj_V_13_8_load,
        din9 => nodes_features_proj_V_13_9_load,
        din10 => nodes_features_proj_V_13_10_load,
        din11 => nodes_features_proj_V_13_11_load,
        din12 => nodes_features_proj_V_13_12_load,
        din13 => nodes_features_proj_V_13_13_load,
        din14 => nodes_features_proj_V_13_14_load,
        din15 => nodes_features_proj_V_13_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_13_fu_2417_p18);

    mux_164_28_1_1_U1955 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_12_0_load,
        din1 => nodes_features_proj_V_12_1_load,
        din2 => nodes_features_proj_V_12_2_load,
        din3 => nodes_features_proj_V_12_3_load,
        din4 => nodes_features_proj_V_12_4_load,
        din5 => nodes_features_proj_V_12_5_load,
        din6 => nodes_features_proj_V_12_6_load,
        din7 => nodes_features_proj_V_12_7_load,
        din8 => nodes_features_proj_V_12_8_load,
        din9 => nodes_features_proj_V_12_9_load,
        din10 => nodes_features_proj_V_12_10_load,
        din11 => nodes_features_proj_V_12_11_load,
        din12 => nodes_features_proj_V_12_12_load,
        din13 => nodes_features_proj_V_12_13_load,
        din14 => nodes_features_proj_V_12_14_load,
        din15 => nodes_features_proj_V_12_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_12_fu_2455_p18);

    mux_164_28_1_1_U1956 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_11_0_load,
        din1 => nodes_features_proj_V_11_1_load,
        din2 => nodes_features_proj_V_11_2_load,
        din3 => nodes_features_proj_V_11_3_load,
        din4 => nodes_features_proj_V_11_4_load,
        din5 => nodes_features_proj_V_11_5_load,
        din6 => nodes_features_proj_V_11_6_load,
        din7 => nodes_features_proj_V_11_7_load,
        din8 => nodes_features_proj_V_11_8_load,
        din9 => nodes_features_proj_V_11_9_load,
        din10 => nodes_features_proj_V_11_10_load,
        din11 => nodes_features_proj_V_11_11_load,
        din12 => nodes_features_proj_V_11_12_load,
        din13 => nodes_features_proj_V_11_13_load,
        din14 => nodes_features_proj_V_11_14_load,
        din15 => nodes_features_proj_V_11_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_11_fu_2493_p18);

    mux_164_28_1_1_U1957 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_10_0_load,
        din1 => nodes_features_proj_V_10_1_load,
        din2 => nodes_features_proj_V_10_2_load,
        din3 => nodes_features_proj_V_10_3_load,
        din4 => nodes_features_proj_V_10_4_load,
        din5 => nodes_features_proj_V_10_5_load,
        din6 => nodes_features_proj_V_10_6_load,
        din7 => nodes_features_proj_V_10_7_load,
        din8 => nodes_features_proj_V_10_8_load,
        din9 => nodes_features_proj_V_10_9_load,
        din10 => nodes_features_proj_V_10_10_load,
        din11 => nodes_features_proj_V_10_11_load,
        din12 => nodes_features_proj_V_10_12_load,
        din13 => nodes_features_proj_V_10_13_load,
        din14 => nodes_features_proj_V_10_14_load,
        din15 => nodes_features_proj_V_10_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_10_fu_2531_p18);

    mux_164_28_1_1_U1958 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_9_0_load,
        din1 => nodes_features_proj_V_9_1_load,
        din2 => nodes_features_proj_V_9_2_load,
        din3 => nodes_features_proj_V_9_3_load,
        din4 => nodes_features_proj_V_9_4_load,
        din5 => nodes_features_proj_V_9_5_load,
        din6 => nodes_features_proj_V_9_6_load,
        din7 => nodes_features_proj_V_9_7_load,
        din8 => nodes_features_proj_V_9_8_load,
        din9 => nodes_features_proj_V_9_9_load,
        din10 => nodes_features_proj_V_9_10_load,
        din11 => nodes_features_proj_V_9_11_load,
        din12 => nodes_features_proj_V_9_12_load,
        din13 => nodes_features_proj_V_9_13_load,
        din14 => nodes_features_proj_V_9_14_load,
        din15 => nodes_features_proj_V_9_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_7_fu_2569_p18);

    mux_164_28_1_1_U1959 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_8_0_load,
        din1 => nodes_features_proj_V_8_1_load,
        din2 => nodes_features_proj_V_8_2_load,
        din3 => nodes_features_proj_V_8_3_load,
        din4 => nodes_features_proj_V_8_4_load,
        din5 => nodes_features_proj_V_8_5_load,
        din6 => nodes_features_proj_V_8_6_load,
        din7 => nodes_features_proj_V_8_7_load,
        din8 => nodes_features_proj_V_8_8_load,
        din9 => nodes_features_proj_V_8_9_load,
        din10 => nodes_features_proj_V_8_10_load,
        din11 => nodes_features_proj_V_8_11_load,
        din12 => nodes_features_proj_V_8_12_load,
        din13 => nodes_features_proj_V_8_13_load,
        din14 => nodes_features_proj_V_8_14_load,
        din15 => nodes_features_proj_V_8_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_6_fu_2607_p18);

    mux_164_28_1_1_U1960 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_7_0_load,
        din1 => nodes_features_proj_V_7_1_load,
        din2 => nodes_features_proj_V_7_2_load,
        din3 => nodes_features_proj_V_7_3_load,
        din4 => nodes_features_proj_V_7_4_load,
        din5 => nodes_features_proj_V_7_5_load,
        din6 => nodes_features_proj_V_7_6_load,
        din7 => nodes_features_proj_V_7_7_load,
        din8 => nodes_features_proj_V_7_8_load,
        din9 => nodes_features_proj_V_7_9_load,
        din10 => nodes_features_proj_V_7_10_load,
        din11 => nodes_features_proj_V_7_11_load,
        din12 => nodes_features_proj_V_7_12_load,
        din13 => nodes_features_proj_V_7_13_load,
        din14 => nodes_features_proj_V_7_14_load,
        din15 => nodes_features_proj_V_7_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_5_fu_2645_p18);

    mux_164_28_1_1_U1961 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_6_0_load,
        din1 => nodes_features_proj_V_6_1_load,
        din2 => nodes_features_proj_V_6_2_load,
        din3 => nodes_features_proj_V_6_3_load,
        din4 => nodes_features_proj_V_6_4_load,
        din5 => nodes_features_proj_V_6_5_load,
        din6 => nodes_features_proj_V_6_6_load,
        din7 => nodes_features_proj_V_6_7_load,
        din8 => nodes_features_proj_V_6_8_load,
        din9 => nodes_features_proj_V_6_9_load,
        din10 => nodes_features_proj_V_6_10_load,
        din11 => nodes_features_proj_V_6_11_load,
        din12 => nodes_features_proj_V_6_12_load,
        din13 => nodes_features_proj_V_6_13_load,
        din14 => nodes_features_proj_V_6_14_load,
        din15 => nodes_features_proj_V_6_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_4_fu_2683_p18);

    mux_164_28_1_1_U1962 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_5_0_load,
        din1 => nodes_features_proj_V_5_1_load,
        din2 => nodes_features_proj_V_5_2_load,
        din3 => nodes_features_proj_V_5_3_load,
        din4 => nodes_features_proj_V_5_4_load,
        din5 => nodes_features_proj_V_5_5_load,
        din6 => nodes_features_proj_V_5_6_load,
        din7 => nodes_features_proj_V_5_7_load,
        din8 => nodes_features_proj_V_5_8_load,
        din9 => nodes_features_proj_V_5_9_load,
        din10 => nodes_features_proj_V_5_10_load,
        din11 => nodes_features_proj_V_5_11_load,
        din12 => nodes_features_proj_V_5_12_load,
        din13 => nodes_features_proj_V_5_13_load,
        din14 => nodes_features_proj_V_5_14_load,
        din15 => nodes_features_proj_V_5_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_3_fu_2721_p18);

    mux_164_28_1_1_U1963 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_4_0_load,
        din1 => nodes_features_proj_V_4_1_load,
        din2 => nodes_features_proj_V_4_2_load,
        din3 => nodes_features_proj_V_4_3_load,
        din4 => nodes_features_proj_V_4_4_load,
        din5 => nodes_features_proj_V_4_5_load,
        din6 => nodes_features_proj_V_4_6_load,
        din7 => nodes_features_proj_V_4_7_load,
        din8 => nodes_features_proj_V_4_8_load,
        din9 => nodes_features_proj_V_4_9_load,
        din10 => nodes_features_proj_V_4_10_load,
        din11 => nodes_features_proj_V_4_11_load,
        din12 => nodes_features_proj_V_4_12_load,
        din13 => nodes_features_proj_V_4_13_load,
        din14 => nodes_features_proj_V_4_14_load,
        din15 => nodes_features_proj_V_4_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_2_fu_2759_p18);

    mux_164_28_1_1_U1964 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_3_0_load,
        din1 => nodes_features_proj_V_3_1_load,
        din2 => nodes_features_proj_V_3_2_load,
        din3 => nodes_features_proj_V_3_3_load,
        din4 => nodes_features_proj_V_3_4_load,
        din5 => nodes_features_proj_V_3_5_load,
        din6 => nodes_features_proj_V_3_6_load,
        din7 => nodes_features_proj_V_3_7_load,
        din8 => nodes_features_proj_V_3_8_load,
        din9 => nodes_features_proj_V_3_9_load,
        din10 => nodes_features_proj_V_3_10_load,
        din11 => nodes_features_proj_V_3_11_load,
        din12 => nodes_features_proj_V_3_12_load,
        din13 => nodes_features_proj_V_3_13_load,
        din14 => nodes_features_proj_V_3_14_load,
        din15 => nodes_features_proj_V_3_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_1_fu_2797_p18);

    mux_164_28_1_1_U1965 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_2_0_load,
        din1 => nodes_features_proj_V_2_1_load,
        din2 => nodes_features_proj_V_2_2_load,
        din3 => nodes_features_proj_V_2_3_load,
        din4 => nodes_features_proj_V_2_4_load,
        din5 => nodes_features_proj_V_2_5_load,
        din6 => nodes_features_proj_V_2_6_load,
        din7 => nodes_features_proj_V_2_7_load,
        din8 => nodes_features_proj_V_2_8_load,
        din9 => nodes_features_proj_V_2_9_load,
        din10 => nodes_features_proj_V_2_10_load,
        din11 => nodes_features_proj_V_2_11_load,
        din12 => nodes_features_proj_V_2_12_load,
        din13 => nodes_features_proj_V_2_13_load,
        din14 => nodes_features_proj_V_2_14_load,
        din15 => nodes_features_proj_V_2_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_s_fu_2835_p18);

    mux_164_28_1_1_U1966 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_1_0_load,
        din1 => nodes_features_proj_V_1_1_load,
        din2 => nodes_features_proj_V_1_2_load,
        din3 => nodes_features_proj_V_1_3_load,
        din4 => nodes_features_proj_V_1_4_load,
        din5 => nodes_features_proj_V_1_5_load,
        din6 => nodes_features_proj_V_1_6_load,
        din7 => nodes_features_proj_V_1_7_load,
        din8 => nodes_features_proj_V_1_8_load,
        din9 => nodes_features_proj_V_1_9_load,
        din10 => nodes_features_proj_V_1_10_load,
        din11 => nodes_features_proj_V_1_11_load,
        din12 => nodes_features_proj_V_1_12_load,
        din13 => nodes_features_proj_V_1_13_load,
        din14 => nodes_features_proj_V_1_14_load,
        din15 => nodes_features_proj_V_1_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_9_fu_2873_p18);

    mux_164_28_1_1_U1967 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_0_0_load,
        din1 => nodes_features_proj_V_0_1_load,
        din2 => nodes_features_proj_V_0_2_load,
        din3 => nodes_features_proj_V_0_3_load,
        din4 => nodes_features_proj_V_0_4_load,
        din5 => nodes_features_proj_V_0_5_load,
        din6 => nodes_features_proj_V_0_6_load,
        din7 => nodes_features_proj_V_0_7_load,
        din8 => nodes_features_proj_V_0_8_load,
        din9 => nodes_features_proj_V_0_9_load,
        din10 => nodes_features_proj_V_0_10_load,
        din11 => nodes_features_proj_V_0_11_load,
        din12 => nodes_features_proj_V_0_12_load,
        din13 => nodes_features_proj_V_0_13_load,
        din14 => nodes_features_proj_V_0_14_load,
        din15 => nodes_features_proj_V_0_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_8_fu_2911_p18);

    mux_164_28_1_1_U1968 : component GAT_compute_one_graph_mux_164_28_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        din2_WIDTH => 28,
        din3_WIDTH => 28,
        din4_WIDTH => 28,
        din5_WIDTH => 28,
        din6_WIDTH => 28,
        din7_WIDTH => 28,
        din8_WIDTH => 28,
        din9_WIDTH => 28,
        din10_WIDTH => 28,
        din11_WIDTH => 28,
        din12_WIDTH => 28,
        din13_WIDTH => 28,
        din14_WIDTH => 28,
        din15_WIDTH => 28,
        din16_WIDTH => 4,
        dout_WIDTH => 28)
    port map (
        din0 => nodes_features_proj_V_15_0_load,
        din1 => nodes_features_proj_V_15_1_load,
        din2 => nodes_features_proj_V_15_2_load,
        din3 => nodes_features_proj_V_15_3_load,
        din4 => nodes_features_proj_V_15_4_load,
        din5 => nodes_features_proj_V_15_5_load,
        din6 => nodes_features_proj_V_15_6_load,
        din7 => nodes_features_proj_V_15_7_load,
        din8 => nodes_features_proj_V_15_8_load,
        din9 => nodes_features_proj_V_15_9_load,
        din10 => nodes_features_proj_V_15_10_load,
        din11 => nodes_features_proj_V_15_11_load,
        din12 => nodes_features_proj_V_15_12_load,
        din13 => nodes_features_proj_V_15_13_load,
        din14 => nodes_features_proj_V_15_14_load,
        din15 => nodes_features_proj_V_15_15_load,
        din16 => trunc_ln1171_1,
        dout => tmp_fu_2949_p18);

    mul_28s_28s_46_1_1_U1969 : component GAT_compute_one_graph_mul_28s_28s_46_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 28,
        din1_WIDTH => 28,
        dout_WIDTH => 46)
    port map (
        din0 => ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275,
        din1 => r_V_reg_3063,
        dout => r_V_8_fu_2999_p2);

    flow_control_loop_pipe_sequential_init_U : component GAT_compute_one_graph_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_448)) then
                if (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_F))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_fu_2949_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_E))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_14_fu_2379_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_D))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_13_fu_2417_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_C))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_12_fu_2455_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_B))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_11_fu_2493_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_A))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_10_fu_2531_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_9))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_7_fu_2569_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_8))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_6_fu_2607_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_7))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_5_fu_2645_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_6))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_4_fu_2683_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_5))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_3_fu_2721_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_4))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_2_fu_2759_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_3))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_1_fu_2797_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_2))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_s_fu_2835_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_1))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_9_fu_2873_p18;
                elsif (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (trunc_ln1169_fu_2337_p1 = ap_const_lv4_0))) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= tmp_8_fu_2911_p18;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_phi_ln1171_reg_2275 <= ap_phi_reg_pp0_iter0_phi_ln1171_reg_2275;
                end if;
            end if; 
        end if;
    end process;

    lhs_fu_622_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    lhs_fu_622 <= ap_const_lv28_0;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    lhs_fu_622 <= ret_V_fu_3016_p2(45 downto 18);
                end if;
            end if; 
        end if;
    end process;

    n2_fu_626_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    n2_fu_626 <= add_ln164_fu_2331_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    n2_fu_626 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln164_reg_3055 <= icmp_ln164_fu_2325_p2;
                r_V_8_reg_3148 <= r_V_8_fu_2999_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln164_fu_2325_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                r_V_reg_3063 <= r_V_fu_2341_p18;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln164_fu_2331_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_n2_2) + unsigned(ap_const_lv5_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_448_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_448 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln164_fu_2325_p2)
    begin
        if (((icmp_ln164_fu_2325_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_phi_reg_pp0_iter0_phi_ln1171_reg_2275 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_n2_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, n2_fu_626)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_n2_2 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_n2_2 <= n2_fu_626;
        end if; 
    end process;

    icmp_ln164_fu_2325_p2 <= "1" when (ap_sig_allocacmp_n2_2 = ap_const_lv5_10) else "0";
    lhs_2_fu_3008_p3 <= (lhs_fu_622 & ap_const_lv18_0);
    r_V_fu_2341_p17 <= ap_sig_allocacmp_n2_2(4 - 1 downto 0);
    ret_V_fu_3016_p2 <= std_logic_vector(unsigned(lhs_2_fu_3008_p3) + unsigned(r_V_8_reg_3148));
    sum_V_4_out <= lhs_fu_622;

    sum_V_4_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln164_reg_3055)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln164_reg_3055 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            sum_V_4_out_ap_vld <= ap_const_logic_1;
        else 
            sum_V_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln1169_fu_2337_p1 <= ap_sig_allocacmp_n2_2(4 - 1 downto 0);
end behav;
