// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module GAT_compute_one_graph_compute_concat (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        out_nodes_features_V_address0,
        out_nodes_features_V_ce0,
        out_nodes_features_V_q0,
        out_nodes_features_skip_concat_bias_V_address1,
        out_nodes_features_skip_concat_bias_V_ce1,
        out_nodes_features_skip_concat_bias_V_we1,
        out_nodes_features_skip_concat_bias_V_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] out_nodes_features_V_address0;
output   out_nodes_features_V_ce0;
input  [27:0] out_nodes_features_V_q0;
output  [12:0] out_nodes_features_skip_concat_bias_V_address1;
output   out_nodes_features_skip_concat_bias_V_ce1;
output   out_nodes_features_skip_concat_bias_V_we1;
output  [27:0] out_nodes_features_skip_concat_bias_V_d1;

reg ap_idle;
reg out_nodes_features_V_ce0;
reg out_nodes_features_skip_concat_bias_V_ce1;
reg out_nodes_features_skip_concat_bias_V_we1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln182_fu_115_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] select_ln182_fu_145_p3;
reg   [6:0] select_ln182_reg_248;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] select_ln182_1_fu_153_p3;
reg   [4:0] select_ln182_1_reg_253;
wire   [63:0] zext_ln184_1_fu_173_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln184_2_fu_219_p1;
reg   [6:0] dim_out_fu_54;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_dim_out_load;
wire   [6:0] add_ln183_fu_178_p2;
reg   [4:0] nd_fu_58;
reg   [4:0] ap_sig_allocacmp_nd_load;
reg   [10:0] indvar_flatten_fu_62;
reg   [10:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [10:0] add_ln182_1_fu_121_p2;
wire   [0:0] icmp_ln183_fu_139_p2;
wire   [4:0] add_ln182_fu_133_p2;
wire   [5:0] trunc_ln184_fu_161_p1;
wire   [10:0] tmp_s_fu_165_p3;
wire   [10:0] tmp_fu_199_p3;
wire   [11:0] tmp_cast_fu_206_p1;
wire   [11:0] zext_ln184_fu_210_p1;
wire   [11:0] add_ln184_fu_213_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

GAT_compute_one_graph_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln182_fu_115_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            dim_out_fu_54 <= add_ln183_fu_178_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            dim_out_fu_54 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln182_fu_115_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_62 <= add_ln182_1_fu_121_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_62 <= 11'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln182_fu_115_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            nd_fu_58 <= select_ln182_1_fu_153_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            nd_fu_58 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln182_fu_115_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln182_1_reg_253 <= select_ln182_1_fu_153_p3;
        select_ln182_reg_248 <= select_ln182_fu_145_p3;
    end
end

always @ (*) begin
    if (((icmp_ln182_fu_115_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_dim_out_load = 7'd0;
    end else begin
        ap_sig_allocacmp_dim_out_load = dim_out_fu_54;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_62;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_nd_load = 5'd0;
    end else begin
        ap_sig_allocacmp_nd_load = nd_fu_58;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_nodes_features_V_ce0 = 1'b1;
    end else begin
        out_nodes_features_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_nodes_features_skip_concat_bias_V_ce1 = 1'b1;
    end else begin
        out_nodes_features_skip_concat_bias_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_nodes_features_skip_concat_bias_V_we1 = 1'b1;
    end else begin
        out_nodes_features_skip_concat_bias_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln182_1_fu_121_p2 = (ap_sig_allocacmp_indvar_flatten_load + 11'd1);

assign add_ln182_fu_133_p2 = (ap_sig_allocacmp_nd_load + 5'd1);

assign add_ln183_fu_178_p2 = (select_ln182_fu_145_p3 + 7'd1);

assign add_ln184_fu_213_p2 = (tmp_cast_fu_206_p1 + zext_ln184_fu_210_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln182_fu_115_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 11'd1216) ? 1'b1 : 1'b0);

assign icmp_ln183_fu_139_p2 = ((ap_sig_allocacmp_dim_out_load == 7'd64) ? 1'b1 : 1'b0);

assign out_nodes_features_V_address0 = zext_ln184_1_fu_173_p1;

assign out_nodes_features_skip_concat_bias_V_address1 = zext_ln184_2_fu_219_p1;

assign out_nodes_features_skip_concat_bias_V_d1 = out_nodes_features_V_q0;

assign select_ln182_1_fu_153_p3 = ((icmp_ln183_fu_139_p2[0:0] == 1'b1) ? add_ln182_fu_133_p2 : ap_sig_allocacmp_nd_load);

assign select_ln182_fu_145_p3 = ((icmp_ln183_fu_139_p2[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_dim_out_load);

assign tmp_cast_fu_206_p1 = tmp_fu_199_p3;

assign tmp_fu_199_p3 = {{select_ln182_1_reg_253}, {6'd0}};

assign tmp_s_fu_165_p3 = {{select_ln182_1_fu_153_p3}, {trunc_ln184_fu_161_p1}};

assign trunc_ln184_fu_161_p1 = select_ln182_fu_145_p3[5:0];

assign zext_ln184_1_fu_173_p1 = tmp_s_fu_165_p3;

assign zext_ln184_2_fu_219_p1 = add_ln184_fu_213_p2;

assign zext_ln184_fu_210_p1 = select_ln182_reg_248;

endmodule //GAT_compute_one_graph_compute_concat
